-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jun 10, 2018 at 04:16 AM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 7.0.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `khabardb`
--
CREATE DATABASE IF NOT EXISTS `khabardb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `khabardb`;

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

CREATE TABLE `contact` (
  `Id` int(4) NOT NULL,
  `Name` varchar(30) NOT NULL,
  `Email` varchar(30) NOT NULL,
  `Message` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `contact`
--

INSERT INTO `contact` (`Id`, `Name`, `Email`, `Message`) VALUES
(1, 'gjmkm', 'ghth@fgbg.com', 'dfsf'),
(2, 'fkldfk', 'ldksv@kdfg.com', 'lfdfldgm'),
(3, 'test', 'test@t.com', 'ttttt');

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

CREATE TABLE `news` (
  `Id` int(11) NOT NULL,
  `Title` varchar(100) NOT NULL,
  `genre` varchar(20) NOT NULL,
  `subGenre` varchar(20) DEFAULT NULL,
  `Content` varchar(1500) NOT NULL,
  `mediaPath` varchar(100) NOT NULL,
  `Date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`Id`, `Title`, `genre`, `subGenre`, `Content`, `mediaPath`, `Date`) VALUES
(22, 'Magufuli leads Tanzanians mourning death of 22 year old conjoined twins', 'WorldNews', 'Africa', 'Tanzaniaâ€™s president John Pombe Magufuli is leading a nation that is mourning the death of 22 year old conjoined twins Maria and Consolata Mwakikuti, who died on Saturday night.\n\nThe much loved twins were admitted to a local hospital in December, after suffering respiratory complications from a chronic heart condition, but only succumbed on Saturday.\n\nMaria and Consolata, who were very popular in Tanzania, were joined from the navel downwards and shared organs like the liver and lungs, had two hearts and separate heads and arms.\n\nMany people took to social media on Sunday to share their condolences to the family, including the president.\n\nMagufuli tweeted that he was â€˜saddened by the deathsâ€™ of women prayed for the nation, when he last visited them at Muhimbili National Hospital.\n\nThe twins won the hearts of people all over the world with their determination to complete higher education, telling the BBC that they wanted to become teachers. At the time of their death, they were taking a teaching degree at Catholic University of Ruaha.\n\nâ€œWe will teach using a projector and computers,â€ they said.\n\nMaria and Consolata, who were against the idea of being surgically separated, were supported by funding from local government and private donations.\n\nThe two, whose parents died while they were still infants, were raised by the Catholic charity Maria Consolata, which had adopted and named them', '../media/Magufuli.jpg', '2018-01-16'),
(27, 'Zimbabwe''s Mnangagwa tells investors ZANU-PF will remain in power', 'WorldNews', 'Africa', 'Zimbabweâ€™s President Emmerson Mnangagwa told foreign investors on Friday that his ruling ZANU-PF party would still be in power after the July elections and dismissed the political opposition as â€œbarking puppiesâ€.\r\n\r\nThe 75-year-old Mnangagwa was propelled into office in November after a de facto military coup ended 94-year-old Robert Mugabeâ€™s near four decades rule.\r\n\r\nMnangagwa has set July 30 for presidential, parliamentary and council elections, which he is counting on to bolster his legitimacy as he pursues a promised break with Mugabeâ€™s repressive policies while trying to woo investors.\r\n\r\nHe told thousands of party supporters in Chegutu town, 100 km (60 miles) west of the capital Harare, that his government was handling many investment requests from Europe, Asia and Arab countries.\r\n\r\nâ€œYes, there are those who come to scout and make arrangements and say â€˜we would like to come in immediately after electionsâ€™. Then we say â€˜you can wait if you want, but those who want to be early birds go aheadâ€™,â€ Mnangagwa said in a speech in the local Shona broadcast on state television.\r\n\r\nâ€œThings are not going to change. Nothing will be different, ZANU-PF is in power and will continue in power.â€\r\n\r\nThe military justified its action in November saying it wanted to remove criminals around Mugabe and arrested some cabinet ministers for corruption.\r\nOpposition plans protests demanding electoral reforms\r\n\r\nMnangagwaâ€™s main challenger in the July vote is 40-year-o', '../media/zimb.jpg', '2018-04-11'),
(28, '''The Reserve Bank should be an independent entity'' - Ramaphosa', 'WorldNews', 'Africa', 'President Cyril Ramphosa has given the strongest indication to date that he wants the independence of the countryâ€™s central bank protected, and he is ready to defend it.\r\n\r\n"I was one of those who participated in the crafting of the clause that deals with the Reserve Bank in our Constitution, and can confirm and testify that to me that remains an unassailable provision in our Constitution," Ramaphosa said.\r\n\r\nThe ANC took a controversial decision to nationalise the South African Reserve Bank (SARB) at its December conference that elected Ramaphosa president of the party.\r\n\r\nHowever, the party delayed a parliamentary debate on full state ownership of the bank in March, when it withdrew a motion on the issue to "allow for more consultation within and with other stakeholders".\r\n\r\nThe countryâ€™s Reserve Bank has private shareholders and the ANC has argued that the current ownership is a "historical anomaly", despite shareholders not having a say on monetary policy.', '../media/The Reserve Bank should be an independent entity - Ramaphosa.mp4', '2018-06-16'),
(29, 'North Koreaâ€™s human rights: What Trump and Kim won''t talk about', 'WorldNews', 'Asia', 'US President Donald Trump and his North Korean counterpart Kim Jong-un will soon be meeting face-to-face, if their historic summit goes ahead.\r\n\r\nThe UN says North Koreans live under "systematic, widespread and gross human rights violations". But human rights will almost certainly not be on the table when the two leaders meet.\r\n\r\nHere are just some of the issues on the back burner for now.\r\nTotal government control\r\n\r\nIsolated from the rest of the world, North Korea has been ruled by the Kim family for three generations, and its citizens are required to pay complete devotion to the family and its current leader, Kim Jong-un.\r\n\r\nThe state controls everything, and actively spies on its citizens using a vast surveillance network.\r\n\r\nThe economy is also strictly controlled and the government funnels money into its nuclear and missile programme despite widespread shortages of food, fuel and other basic necessities.\r\n\r\nBrad Adams, Asia director of Human Rights Watch (HRW), told the BBC that North Korea has only been able to develop an expensive nuclear programme because it is a totalitarian state, and it''s done so by "taking food out of the stomachs of hungry North Koreans".', '../media/asia1.jpg', '2018-03-14'),
(30, 'Restoring life to the Aral Sea''s dead zone', 'WorldNews', 'Asia', 'The loss of the Aral Sea in central Asia is an ecological disaster. Toxic chemicals in the exposed sea bed have caused widespread health problems. Can an ambitious project to plant millions of trees save the Karakalpak people of Uzbekistan?\r\n\r\nSeventy-eight-year-old Almas Tolvashev shuffles through the sand towards the rusting hulk of a fishing boat.\r\n\r\nThe lighthouse that keeps watch over a crumbling flotilla of 10 or so ships is a stark reminder that Moynaq was once a thriving fishing port on the Aral Sea.\r\n\r\n"The history of the Karakalpak people starts with the sea," says the former fisherman. "Fishing was the first thing fathers taught their sons".\r\n\r\nMoynaq lies at the heart of Karakalpakstan, a semi-autonomous republic within Uzbekistan. In its heyday, this is where 98% of Uzbekistan''s fish came from. \r\n"I was the first Muslim captain in Moynaq and my ship was the Volga. Captains were usually ethnic Russians," Almas says proudly.\r\n\r\n"There were 250 ships here. I used to catch 600-700 kilos of fish every day. Now there is no sea".\r\n\r\n    Waiting for the sea\r\n    How Soviet pollution destroyed the Aral Sea\r\n\r\nThe Aral Sea started to shrink in the 1960s when the Soviets diverted water from the two main rivers that flowed into the Aral Sea to feed vast new cotton fields.\r\n\r\nAs cotton production boomed, the Kremlin refused to acknowledge the problem. Locals had to put labelled sticks in the ground to prove the shoreline was disappearing.\r\nAs the volume of water decreased, th', '../media/asia2.jpg', '2018-06-14'),
(31, 'Sultan of Yogyakarta: A feminist revolution in an ancient kingdom', 'WorldNews', 'Asia', 'The Sultan of Yogyakarta holds a powerful political and spiritual position on the Indonesian island of Java. He is manoeuvring to make his eldest daughter his heir, sparking a bitter feud, as the BBC''s Indonesia editor Rebecca Henschke reports.\r\n\r\n"From generation to generation the sultan who reigns over Yogyakarta seems to adapt himself to the changing of times," says Wedono Bimo Guritno quietly as he ushers me through the elaborate palace complex.\r\n\r\nHe is one of the nearly 1,500 abdi dalam, members of the royal court. A keris, a sacred Javanese dagger, is tucked into his sarong.\r\n\r\n"In the past it was not difficult to choose a prince, because in the past, the sultan had more than one wife," Wedono Bimo Guritno tells me. We duck under low gateways into a maze of tree-lined courtyards surrounding the Kraton Kilen, the Sultan''s private residence.\r\n\r\n"But you know it''s always been women that hold the real power in Javanese households," Bimo says with a smile.\r\nAs is required of anyone entering the palace, I have been traditionally dressed and groomed for over an hour. I am in a tight batik sarong, with a black silk blouse known as a kebaya. My hair has been pulled back and tied into tight bun, a sanggul.\r\n\r\nEverything in this palace, from the placement of trees to the movements made by the royal court, has meaning.\r\n\r\nIn Javanese culture, things are not said directly, but instead conveyed by symbolism.\r\n\r\nThe sultan, who is 72, recently changed his own title so that it is gend', '../media/asia3.jpg', '2018-06-05'),
(32, 'Richard Grenell, US envoy to Germany, wants to ''empower'' Europe''s right', 'WorldNews', 'Europe', 'The US ambassador to Germany has said he wants to "empower" Europe''s right.\r\n\r\nRichard Grenell, who was appointed by President Donald Trump last year, made the highly unusual comments for a diplomat to right-wing Breitbart News.\r\n\r\n"I think there is a groundswell of conservative policies that are taking hold because of the failed policies of the left," he said.\r\n\r\nMr Grenell''s comments follow several other controversial remarks by Trump-appointed diplomats.\r\nIn the interview, the ambassador, who only took office last month, said President Trump''s election had energised people to take on the "political class". Mr Grenell said he had been contacted by people throughout Europe about a conservative "resurgence".\r\n\r\nHe attacked the perceived bias of the media and politicians against Mr Trump as "the group-think of a very small elitist crowd", and praised Austria''s conservative Chancellor Sebastian Kurz as a "rock star".\r\n\r\nMr Kurz''s party formed a coalition with the far-right Freedom Party in 2017.\r\n\r\nRight-wing populists have won support across Europe, with recent electoral success for parties in Italy and Slovenia that espouse strict immigration policies.\r\n\r\nDemocratic Senator Chris Murphy described the interview as "awful".\r\n\r\nIn a tweet, he said he had previously spoken to Mr Grenell about "politicising this post".', '../media/ur1.jpg', '2018-06-05'),
(33, 'Israel''s Netanyahu tours Europe to lobby leaders against Iran', 'WorldNews', 'Europe', 'Benjamin Netanyahu has embarked on a three-day trip to Europe to push leaders in Germany, France and Britain away from the Iran nuclear deal and convince them of the need to dislodge Tehranâ€™s military from neighbouring Syria.\r\n\r\nThe Israeli prime minister has signalled a desire to keep talks focused on his archenemy. â€œI will meet there with three leaders and will discuss two subjects: Iran and Iran,â€ he said at the airport ahead of his trip on Monday.\r\n\r\nHowever, the 68-year-old leader is likely to face queries about the Israeli militaryâ€™s recent use of live fire against Palestinian protesters in Gaza.\r\n\r\nTroops have killed more than 120 people along the frontier and shot thousands more during two months of rallies calling, among other demands, for an end to Israelâ€™s blockade of the coastal enclave.\r\nEhud Barak on the crisis in Israel: â€˜Netanyahu has to resignâ€™\r\nRead more\r\n\r\nThe army points to attempts to damage the perimeter fence with explosives and set fields alight in Israel using firebombs, moves that undermine claims by Gazaâ€™s rulers Hamas that the movement is entirely peaceful. However, most of the dead and wounded were unarmed. On Friday, a female volunteer medic was shot dead.\r\n\r\nNetanyahu flew on Monday morning to Berlin, where he is due to meet Angela Merkel, before flying to Paris to speak with Emmanuel Macron on Tuesday. He will then travel to Britain for a meeting with Theresa May.\r\n\r\nHis visit follows a diplomatic victory last month when the US ', '../media/ur2.jpg', '2018-06-12'),
(34, 'Netherlands to host fifth Invictus Games in 2020', 'WorldNews', 'Europe', 'The fifth Invictus Games will be held in the Netherlands in 2020, the Duke of Sussex has announced.\r\n\r\nThe Hague will host the event in which wounded military veterans compete in a Paralympic-style event.\r\n\r\nThe duke, who founded the games, said: "The city will soon become the motivation for hundreds of servicemen and women."\r\n\r\nIn October, the Duke and Duchess of Sussex will travel to Sydney, Australia for the fourth Invictus Games.\r\n\r\n"The Netherlands has supported the Games from the very beginning, and I know that everyone there will fully get behind and support then soldiers and veterans who have served their countries so bravely," Prince Harry said.\r\n\r\nThe event has previously been held in London (2014), Orlando (2016) and Toronto (2017).\r\n\r\nThe 2020 games were awarded to the Hague following a competitive tender process.\r\nInvictus Games Foundation chairman Sir Keith Mills said the Hague''s bid "exemplified the Invictus spirit".\r\n\r\n"Post-War, the Hague has undergone its own process of rebuilding and rehabilitation, a theme many of those competing can intimately relate to," he added.\r\n\r\nMart de Kruif, a retired lieutenant general who is chairman of the Hague Games, said: "2020 is an important milestone for the Netherlands, marking 75 years since liberation.\r\n\r\n"The Invictus Games provides the perfect opportunity for us to link the past to the present by paying a tribute to wounded, injured and sick service personnel who served, and are serving, the military."', '../media/ur3.jpg', '2018-05-09'),
(35, 'Trump ''could pardon himself over Russia but won''t'', says Giuliani', 'WorldNews', 'USCanada', 'Donald Trump probably has the power to pardon himself in the Russia collusion affair but does not intend to do so, his lawyer Rudy Giuliani says.\r\n\r\nA special counsel is investigating Russia''s role in the 2016 election, and whether Mr Trump obstructed justice.\r\n\r\nThe question of self-pardon arose after the New York Times published a letter to the counsel from Mr Trump''s lawyers.\r\n\r\nIn it they say he has absolute power as US legal chief to end investigations, or "even exercise his power to pardon".\r\n\r\nSuch absolute powers, they argue, mean that he could not have obstructed justice in any case.\r\nWhat has Mr Giuliani said?\r\n\r\nHe appeared on ABC''s This Week programme and was asked whether Mr Trump had the power to pardon himself.\r\n\r\nMr Giuliani, the head of Mr Trump''s legal team, said he "probably does", but added: "He has no intention of pardoning himself."\r\n\r\nHe went on: "I think the political ramifications of that would be tough. Pardoning other people is one thing. Pardoning yourself is another."\r\n\r\nSpeaking on CNN on Sunday, House Republican Majority Leader Kevin McCarthy said that no president should pardon himself.\r\nWhy would Mr Trump need to pardon himself?\r\n\r\nIt all stems from the investigation by special counsel Robert Mueller into alleged collusion between the Trump team and Russian officials in the election campaign that brought the president to power.', '../media/us1.jpg', '2018-06-05'),
(36, 'Dancing FBI agent drops gun during backflip and shoots man in leg', 'WorldNews', 'USCanada', 'An off-duty FBI agent accidentally shot a bystander in the leg when his gun fell from its holster as he cavorted on the dance-floor of a bar in Denver, Colorado, police said.\r\n\r\nVideo widely shared on Twitter shows the agent strutting his stuff and then performing a backflip.\r\n\r\nThe gun falls to the floor and, as the agent goes to grab it, fires a shot.\r\n\r\nThe fellow customer hit by the bullet was taken to hospital with a non-life-threatening injury.\r\n\r\nIt is unclear if the agent, who has not been named, will face charges or disciplinary action.\r\nThe video shows that his wild moves on the dance-floor had attracted an appreciative crowd at the Mile High Spirits and Distillery bar on Saturday night.\r\n\r\nBut the mood quickly changed when the gun went off. As shocked patrons look on, the agent retrieves his weapon, holds up his hands and leaves the floor.\r\n\r\nDenver Police Department said the agent "was dancing at a nightclub when his firearm became dislodged from its waistband holster and fell on to the floor. When the agent retrieved his handgun an unintended discharge occurred".\r\n\r\nThe statement added: "The victim was transported to the hospital with a good prognosis."\r\n\r\nPolice spokeswoman Marika Putnam said the agent was taken to a police station and later released to an FBI supervisor.\r\n\r\nThe Denver District Attorney''s office said the incident remained under investigation.\r\n The link to video : https://twitter.com/RyanHaarer/status/1003084052226822153', '../media/us2.jpg', '2018-05-17'),
(37, 'Why Bill Clinton has written a thriller novel with James Patterson', 'WorldNews', 'USCanada', 'Bill Clinton says he "loved" being president of the United States. Now he has teamed up with the world''s bestselling novelist, James Patterson, to write a political thriller that draws on his time in the White House, called The President is Missing.\r\n\r\n"I love thrillers," says the former president. "I read huge numbers of them. I''ve just finished the third book in the Red Sparrow trilogy [by Jason Matthews]."\r\n\r\nHe''s "a fan" of Patterson''s work too and has "devoured" all 25 of his books featuring the detective-turned-psychologist Alex Cross.\r\n\r\n"I didn''t read much murder fiction or thrillers until the early 1980s and I just got into them," adds the man who was elected president in 1992 and served for two terms.\r\n\r\nThroughout that time, he had been harbouring a dream to write one himself. "I''d always wanted to do it," he explains.\r\n\r\nIt is the first time a former US president has written a thriller.\r\nWhat is the book about?\r\n\r\nFrom the bowling alley in the basement of the White House to the treadmill in the president''s bedroom, "we really tried to make it as accurate as possible", Clinton says.\r\n\r\nBut as well as insider details, the book aims to show what it would be like to president in the most extreme circumstances. It may be a novel, but it is about "things that could happen".\r\n\r\nThe plot revolves around a devastating cyber attack on the US, which threatens to bring the world to its knees. With the clock ticking, the president disappears. \r\nBeing president can be "the most', '../media/us3.jpg', '2018-06-05'),
(38, 'Nicaragua police end church siege after day of terror in Masaya', 'WorldNews', 'Latin', 'Police in Nicaragua have ended the siege of a church where opposition supporters had sought refuge after being attacked by riot police and pro-government militias.\r\n\r\nDoctors have been allowed to treat the injured inside the church in the city of Masaya. Two people have died.\r\n\r\nSome 30 people who were inside the church were released after the local Catholic Church intervened.\r\n\r\nMore than 100 people have been killed in Nicaragua in six weeks of violence.\r\n''No more repression!"\r\n\r\nMonsignor Silvio JosÃ© BÃ¡ez, the auxiliary bishop of Managua, praised the local priest in Masaya, Edwing Roman, and a human rights lawyer and campaigner, Ãlvaro Leiva, for their efforts in negotiating with the authorities.\r\n\r\nHe urged President Daniel Ortega to end the crackdown on protests against his government.\r\n\r\nMonsignor BÃ¡ez earlier took to social media to warn people to stay indoors, because there were reports of snipers on the streets of Masaya. \r\n"The priests in Masaya have told me that the San Miguel parish is surrounded by anti-riot police," he wrote on Twitter.\r\n', '../media/l1.jpg', '2018-06-05'),
(39, 'Brazil Petrobras oil boss Pedro Parente resigns amid protests', 'WorldNews', 'Latin', 'The head of Brazil''s oil giant Petrobras, Pedro Parente, has resigned, following a nationwide strike by lorry drivers that caused huge disruption.\r\n\r\nThe strike against diesel prices, which ended this week, caused major shortages in the country.\r\n\r\nMany of the protesters blamed Mr Parente for rising costs, after the company stopped subsidising fuel prices for its domestic consumers.\r\n\r\nHowever, Petrobras gave no specific reason for the resignation.\r\n\r\nIn his resignation letter to President Michel Temer, Mr Parente said the strike challenged the pricing policy he had implemented.\r\n\r\nMr Parente said his role "as CEO had stopped being positive" and the government needed to consider "alternatives" to its pricing policy going forward, according to Reuters news agency.\r\n\r\nTwo years ago, former energy minister Mr Parente pegged the price of fuel in Brazil to international oil prices, which have since almost doubled.\r\n\r\nAfter years of corruption scandals involving senior politicians and officials, his policy had helped Petrobras recover its market value.\r\n\r\n    A quick guide to Brazil''s scandals\r\n    Brazil fuel prices cut in effort to halt strike\r\n\r\nThe oil giant is controlled by the Brazilian government and is regarded as one of the world''s biggest oil companies.\r\n\r\nIn January, the company agreed to pay almost $3bn (Â£2.18bn) to settle a class action suit in the United States, after investors said their holdings were damaged by a corruption scandal facing the firm.\r\n\r\nBrazil''s gove', '../media/l2.jpg', '2018-06-03'),
(40, '''Non-heterosexuals'' message causes stir in Colombia', 'WorldNews', 'Latin', 'A video posted by Colombia''s former president Alvaro Uribe Velez has been widely criticised on social media after he described the LGBTI community in Colombia as "non-heterosexuals".\r\n\r\nMr Uribe posted a video message on his Facebook and Twitter accounts on Thursday night, encouraging gay people to vote for Ivan Duque, a conservative presidential candidate, and Marta Lucia Ramirez, Mr Duque''s vice-president pick, in the second round of the Colombian presidential election.\r\n\r\nIn his video, Mr Uribe, who is still hugely influential, was flanked by a group of people with a rainbow flag at the back. \r\nHe said that, from a personal standpoint and because of his political responsibility in the Centro Democratico party, he wanted to express his support for marriage rights, adoption rights, abortion rights and rights of faith.\r\n\r\nHowever, his use of the expression "non-heterosexuals" has upset Colombians.\r\n\r\nYou may be also interested in:\r\n\r\n    Arkady Babchenko: The plot twist that ''crossed the line''\r\n    Roseanne Barr''s tweet and shelved sitcom sparks debate\r\n    Saudi Arabia to criminalise sexual harassment\r\n\r\nAt time of writing, the hashtag #ColombianosNoHeterosexuales has been used more than 18,000 times on Twitter. Mr Uribe''s video is also posted on his official Facebook page and has been shared over 1,000 times.\r\n\r\n"What a joy to belong to the non-Uribe Colombians", wrote Daniel Samper Ospina, a journalist and YouTuber, mocking the expression.\r\n\r\nTwitter user Daniela used a va', '../media/l3.jpg', '2018-06-01'),
(41, 'Are you scared yet? Meet Norman, the psychopathic AI', 'Tech', NULL, 'Norman is an algorithm trained to understand pictures but, like its namesake Hitchcock''s Norman Bates, it does not have an optimistic view of the world.\r\n\r\nWhen a "normal" algorithm generated by artificial intelligence is asked what it sees in an abstract shape it chooses something cheery: "A group of birds sitting on top of a tree branch."\r\n\r\nNorman sees a man being electrocuted.\r\n\r\nAnd where "normal" AI sees a couple of people standing next to each other, Norman sees a man jumping from a window.\r\n\r\nThe psychopathic algorithm was created by a team at the Massachusetts Institute of Technology, as part of an experiment to see what training AI on data from "the dark corners of the net" would do to its world view.\r\n\r\nThe software was shown images of people dying in gruesome circumstances, culled from a group on the website Reddit.\r\n\r\nThen the AI, which can interpret pictures and describe what it sees in text form, was shown inkblot drawings and asked what it saw in them.\r\n\r\nThese abstract images are traditionally used by psychologists to help assess the state of a patient''s mind, in particular whether they perceive the world in a negative or positive light.\r\n\r\nNorman''s view was unremittingly bleak - it saw dead bodies, blood and destruction in every image.\r\n\r\nAlongside Norman, another AI was trained on more normal images of cats, birds and people.\r\n\r\nIt saw far more cheerful images in the same abstract blots.\r\n\r\nThe fact that Norman''s responses were so much darker illustrates a ', '../media/tech1.jpg', '2018-06-05'),
(42, 'Tech Tent: Can AI make it to number one?', 'Tech', NULL, 'How close are we to hearing a song composed by a computer making it to number one in the charts? On this week''s Tech Tent, we meet the musician who hopes she can make that happen.\r\n\r\nTaryn Southern has been working with artificial intelligence tools for some years. Her single Break Free was composed with the help of AI tools.\r\n\r\nOf course, musicians have been adopting all kinds of technology for years, and using computers to generate or enhance new music is not new.\r\n\r\nBut Taryn says her work with AI is different because the feedback loop enables the computer and the artist to learn from each other.\r\n\r\n"Once the AI exports a song and the artist makes changes, the neural network can learn from their suggestions and start to develop a taste for the artist''s preferences," she explains.\r\n\r\nWhile Taryn is a pop artist, the AI she uses has been trained on thousands of hours of piano pieces from the 18th Century and searches for patterns in them.\r\n\r\nThat means it has different influences to her own. "If I grew up listening to the Beatles and Britney Spears and N-Sync, chances are that I''m going to be drawn to making music more in that style," she explains.\r\n\r\n"By working with an AI that is trained to find patterns that my own brain cannot find, that forces me as an artist to think out of the box."', '../media/tech2.jpg', '2018-06-05'),
(43, 'Facebook losing out to YouTube, Instagram and Snapchat among US teens', 'Tech', NULL, 'US teenagers are ditching Facebook in favour of platforms such as YouTube, Instagram and Snapchat, a study says.\r\n\r\nOnly 51% use Facebook, which is a 20 percentage point drop since 2015, when the US-based Pew Research Center last surveyed teens'' social media habits.\r\n\r\nMost of those aged 13 to 17 own or have access to a smartphone, with 45% online on a near-constant basis.\r\n\r\nYouTube has stolen Facebook''s former dominance over teens, with 85% of them preferring the video-sharing platform.\r\n\r\nSecond and third top social media services among teens are now Instagram at 72% and Snapchat at 69%.\r\n\r\nThe numbers of teens who use Twitter (32%) and Tumblr (14%) are largely unchanged compared to the results found in 2015.\r\n\r\n    Facebook ''no place'' for young children\r\n    Is social media making your child sad?\r\n    Social media rights explained to teens\r\n\r\nWhile Facebook may have lost its reign among the teenage demographic to Google-owned YouTube, it has owned the rising favourite Instagram, a photo and video-sharing networking service, since 2012.\r\nUS teenagers are ditching Facebook in favour of platforms such as YouTube, Instagram and Snapchat, a study says.\r\n\r\nOnly 51% use Facebook, which is a 20 percentage point drop since 2015, when the US-based Pew Research Center last surveyed teens'' social media habits.\r\n\r\nMost of those aged 13 to 17 own or have access to a smartphone, with 45% online on a near-constant basis.\r\n\r\nYouTube has stolen Facebook''s former dominance over teens, with ', '../media/tech3.jpg', '2018-06-03'),
(44, ' Vincent Kompany selected in Belgium squad for World Cup ', 'Sports', 'Football', 'Vincent Kompany has been named in Belgium''s World Cup squad despite picking up an injury on Saturday.\r\n\r\nBut Crystal Palace forward Christian Benteke has been left out of the squad, which manager Roberto Martinez has reduced from 28 to 23.\r\nKompany is fresh from leading Manchester City to the Premier League title but picked up a groin injury during the 0-0 draw with Portugal in Brussels on Saturday.\r\n\r\nBelgium begin their World Cup campaign against Panama on June 18 and Martinez will give Kompany as much time as possible to regain his fitness.\r\n\r\n"I think the situation is very clear," said Martinez.\r\n\r\n"We are going to try to use the rules to our advantage. We need to name the outfield players squad 24 hours before Panama, that is the 17th of June.\r\n\r\n"So, until then we are going to try to give the maximum time to see what the reaction is with Vinny.\r\n\r\n"I think in any player, maybe a scan would reveal what the extent of the problem is.\r\n\r\n"With Vinny Kompany, we have spoken very closely with Manchester City, and experience over the last few years is that Vinny''s reactions to certain soft tissue injuries, they cannot describe via scan.', '../media/foot1.jpg', '2018-06-04'),
(45, ' Sunday Supplement at the World Cup: Special podcast from Russia ', 'Sports', 'Football', 'The Sunday Supplement is going to the World Cup!\r\n\r\nWe''ll be bringing you the best insight, reaction and analysis to the major stories in Russia with the World Cup Supplement podcast.\r\n\r\nHost Neil Ashton will be joined by journalists covering the tournament for a series of podcasts over the course of the competition.\r\n\r\nThey''ll be giving you the stories behind the stories, with detailed discussion about England''s campaign as well as reflections on how the other contenders are faring and the off-field developments making the news.\r\n\r\nWe''ll be kicking off with a preview podcast ahead of the World Cup and then have shows regularly throughout the next month from the tournament.\r\n\r\nIf you''re already a Sunday Supplement podcast subscriber, you''ll receive the special World Cup Supplement podcast directly to your device.\r\n\r\nIf not, you can sign up to receive each show via iTunes here.\r\n\r\nWe''ll also be publishing each podcast on skysports.com/podcasts\r\n\r\nRemember, you can have your say on the big football stories by tweeting @SundaySupp', '../media/foot2.jpg', '2018-06-05'),
(46, 'Mohamed Salah included in Egypt''s World Cup squad despite injury', 'Sports', 'Football', 'Mohamed Salah has been included in Egypt''s final 23-man squad for the World Cup, despite the injury he sustained in the Champions League final.\r\n\r\nThe Liverpool forward suffered a shoulder injury after a challenge by Real Madrid defender Sergio Ramos in the first half in Kiev, but is now set to play for his country at the tournament in Russia later this month.\r\n\r\nSalah has been receiving treatment in Valencia and posted a picture on Twitter on Tuesday of himself in the gym with the caption "good feelings".\r\n\r\nThe Egyptian Football Federation previously said it did not expect the 25-year-old to be out for more than three weeks.\r\n\r\nA post on its Facebook page said it was being kept aware of Salah''s recovery, as well as the "determination of the great player to catch up with his team-mates".\r\n\r\nEgypt begin their World Cup campaign against Uruguay on June 15, and will also face Saudi Arabia and hosts Russia in group A.', '../media/foot3.jpg', '2018-06-06'),
(47, 'French Open 2018: Serena Williams ''has no negative feelings'' towards Maria Sharapova', 'Sports', 'Tennis', 'Serena Williams says she does not have any negative feelings towards Maria Sharapova and is surprised the Russian''s recent autobiography was so much about her.\r\n\r\nWilliams described the book as "100% hearsay" and said women should encourage each other rather than detailing locker-room incidents in a less than positive light.\r\n\r\nThe pair will meet in the fourth round of the French Open on Monday in their first match since the 2016 Australian Open, with the contest expected to start about 15:00 BST on Court Philippe-Chatrier.\r\n\r\nWilliams has won their last 18 meetings, with Sharapova''s only two victories coming in 2004.\r\n\r\nAnd it was the first of those - in the Wimbledon final - that Sharapova believes was the catalyst for Williams'' domination since.\r\n\r\n    Edmund beaten by Fognini in third round\r\n    Defending champion Nadal eases into last 16\r\n    Kvitova out as Halep and Muguruza advance\r\n    Live scores, schedule and results\r\n\r\n"I think Serena hated me for being the skinny kid who beat her, against all odds, at Wimbledon," she wrote in her 2017 autobiography ''Unstoppable: My Life So Far''.\r\n\r\n"I think she hated me for seeing her at her lowest moment. But mostly I think she hated me for hearing her cry. She''s never forgiven me for it."\r\n\r\nWilliams gave her first response to the book as she faced questions following her straight-set third-round victory over Julia Gorges in Paris.\r\n\r\n"I think the book was 100% hearsay, which was a little bit disappointing," she said.\r\n\r\n"I have', '../media/tens1.jpg', '2018-06-04'),
(48, 'French Open 2018: Marco Trungelliti hopes for a less stressful drive home', 'Sports', 'Tennis', 'Lucky loser Marco Trungelliti hopes his drive home will have "less stress" than the 10-hour dash he made on Sunday to reach the French Open.\r\n\r\nThe Argentine, 27, drove from Barcelona to Paris with his grandmother, mother and brother to earn a first-round spot.\r\n\r\nHe beat Bernard Tomic on Monday, only to lose in straight sets against Italy''s Marco Cecchinato on Wednesday.\r\n\r\n"It''s been a different experience with all the media," he said. "But I enjoyed it. I''ve never been here before."\r\n\r\n    Djokovic books place in third round\r\n    Zverev & Dimitrov survive five-set battles\r\n    Live scores, schedule and results\r\n    Alerts: Get tennis news sent to your phone\r\n\r\nTrungelliti - and his 89-year-old grandmother Daphne - became the centre of attention at Roland Garros after his wife posted pictures of them, along with his mother Susanna and brother Andre, travelling and singing during their journey to the French capital.\r\n\r\nHe then described after his four-set win over Tomic that he had to tell his grandma to get out of the shower so they could leave his home in Barcelona.\r\n\r\nThe world number 190 lost in Roland Garros qualifying last week, but returned in a race to sign in as a lucky loser after Australian Nick Kyrgios pulled out with injury.\r\n\r\nNow he will drive back to the Spanish city in a few days'' time - having earned Â£69,000 from his trip to Paris.\r\n\r\n"It has been amazing because I won on Monday, if I''d come here and lost it would have been tough mentally," he added.\r\n\r\n"B', '../media/tens2.jpg', '2018-06-04'),
(49, 'Tennis could have reason to make matches shorter: Your shrinking attention span ', 'Sports', 'Tennis', 'Novak Djokovic called it the greatest match of his life.\r\n\r\nRafael Nadal called it his toughest defeat, as well as the best match he''d ever played.\r\n\r\nAnd a parade of past tennis champions - Andre Agassi, Boris Becker and Pete Sampras among them - called it the best they''d ever seen after Djokovic collapsed on his back, overcome by exhaustion and euphoria, upon vanquishing Nadal in the marathon 2012 Australian Open final.\r\n\r\nWhat set the match apart was its sustained excellence as the world''s No.1 and 2 players answered each other''s offensive fireworks with defensive heroics over a 5-hour, 53-minute, five-set final that kept fans in the stands of Melbourne''s Rod Laver Arena until 1:35 a.m.\r\nBut five-set matches aren''t always riveting, particularly in the early stages of Grand Slam events. Many are settled by attrition: Whose legs last longer? Who can avoid being seized by cramps, as American Jared Donaldson was in his five-set loss to Grigor Dimitrov on Wednesday, forced to serve underhanded before succumbing in the second round of the French Open.\r\n\r\nDebate over the wisdom of the format pops up from time to time, typically rekindled by angst over injuries to star players or a reexamination of gender equity: Why should men play best-of-five-set matches in the Slams when women play best-of-three?\r\nBut as tennis seeks to keep pace in today''s fast-moving, time-starved world, there''s new reason for a fresh look at five-set matches: Audience attention spans.\r\n\r\nVenture capitalist ', '../media/tens3.jpg', '2018-06-06'),
(50, 'Curry sinks NBA Finals record nine 3-pointers in Warriors romp', 'Sports', 'Basketball', 'OAKLAND, United States: Stephen Curry scored 33 points, sinking an NBA Finals record nine 3-pointers in the process, and the Golden State Warriors moved halfway to their third title in four seasons on Sunday (Jun 4) by beating Cleveland 122-103.\r\n\r\nThe Warriors, who never trailed, seized a 2-0 lead in the best-of-seven series, which shifts to Cleveland for games three and four on Wednesday and Friday.\r\n\r\n"We''ve got to get that same focus going to Cleveland," Curry said.\r\n\r\nCurry, a 30-year-old guard, broke the old mark of eight 3-pointers in a finals game set by Ray Allen of Boston in 2010.\r\n\r\n"To be on top of that 3-point list is pretty special," Curry said.\r\n\r\nCurry scored 16 points in the fourth quarter, including a 4-point play from a corner 3-pointer and the record breaker from the left side with 3:30 remaining.\r\n\r\nHe finished by shooting 11-of-26 from the floor, 9-of-17 from 3-point range, with seven rebounds and eight assists.\r\n\r\nKevin Durant added 26 points, Klay Thompson had 20 and JaVale McGee added 12 to spark the Warriors.\r\n\r\nCavaliers superstar LeBron James netted 29 points with 13 assists and nine rebounds while Kevin Love added 22 points and 10 rebounds, but Cleveland came no closer than five points in the second half.\r\n\r\nThe Cavaliers and Warriors are meeting for the fourth consecutive NBA Finals, with Golden State having won titles in 2015 and 2017 while Cleveland captured the 2016 crown, rallying from a 3-1 deficit in the greatest comeback in finals history.', '../media/bask1.jpg', '2018-06-04'),
(51, 'Cannabis and sport: NBA winner Matt Barnes ''smoked before games''', 'Sports', 'Basketball', '"I would smoke cannabis six hours before a game. We''d have a shoot-around in the morning, I''d come home and smoke a joint, take a nap, shower, eat and go and play."\r\n\r\nMatt Barnes won the NBA with Golden State Warriors last year after following that pre-game routine.\r\n\r\nThe 38-year-old retired last June after the 4-1 series win over Cleveland Cavaliers and has told BBC Sport that use of the banned substance is "widespread" despite being in breach of NBA rules.\r\n\r\nBarnes says he even discussed cannabis with his coach, seven-time NBA champion Steve Kerr, who has previously admitted to taking the drug to ease chronic back pain.\r\n\r\nBut is using a substance that is legal for medical use in 29 states and recreationally in nine of those really so prevalent in one of the most moneyed sports leagues in the world?\r\n\r\nIf so, how are players getting away with it? And what is the NBA doing about it?\r\n\r\nWhy are players using cannabis?\r\n\r\nCannabis has been a part of Barnes'' life since he was 14, but he refutes suggestions that he is addicted.\r\n\r\nDuring his 14 seasons in the NBA with seven different teams, he used it to manage pain, to relax and to help him sleep, and says it "brought me peace of mind".\r\n\r\nThe story is echoed by several of Barnes'' contemporaries in a sport where athletes are often asked to play several high-intensity matches in distant cities within the space of a few days.\r\n\r\nFormer NBA power forward Kenyon Martin, in an interview with Bleacher Report in April, estimated th', '../media/bask2.jpg', '2018-06-05'),
(52, 'NBA Finals: Golden State Warriors beat Cleveland Cavaliers in overtime in game one', 'Sports', 'Basketball', 'Defending champions Golden State Warriors took a 1-0 lead in the NBA Finals with a controversial 124-114 overtime win against Cleveland Cavaliers, despite a 51-point haul from LeBron James.\r\n\r\nLate in the fourth quarter, Cavaliers'' JR Smith ran down the clock instead of attempting a game-winning shot.\r\n\r\nThe Warriors dominated overtime at the Oracle Arena in Oakland.\r\n\r\nGame two in the best-of-seven series takes place in Oakland on Sunday night.\r\n\r\nStephen Curry scored 29 points for Golden State, who beat the Cavaliers in the first game of the finals for the fourth year in a row.\r\n\r\nJames, playing in his eighth successive finals, claimed his best play-off points haul - the highest since Michael Jordan scored 55 in 1993.\r\n\r\n"It was epic, and he did enough to carry this team to a victory," said Cavaliers coach Tyronn Lue. "To do what he did tonight and come out robbed, it''s just not right."\r\n\r\nWith 36.4 seconds remaining in the fourth quarter, Kevin Durant was called for an offensive foul on James, but the decision was reversed on review.\r\n\r\nDurant levelled the game from the free-throw line, before James put the Cavaliers back in front.\r\n\r\nCurry scored a three-pointer as the Warriors opened up a one-point lead.\r\n\r\nIn the final seconds, with the scores level a 107-107, George Hill missed the second of his two free throws for the Cavaliers. But Smith grabbed the offensive rebound and ran away from the Warriors'' basket.\r\n\r\n"He thought we were up one," said Lue, although Smith said', '../media/bask3.jpg', '2018-06-05'),
(53, 'Microsoft buys code-sharing site Github for $7.5bn', 'Business', NULL, 'Microsoft has announced it is to acquire the code-sharing site Github.\r\n\r\nGithub, based in San Francisco, is an online platform that allows coders to collaborate with each other on their work.\r\n\r\nIt is used by employees at many big companies, including Microsoft.\r\n\r\nMicrosoft said it was paying $7.5bn (Â£5.6bn) in stock to achieve the deal, which is due to be completed before the end of the year. It said Github would continue to operate independently.\r\n\r\n"We recognise the community responsibility we take on with this agreement and will do our best work to empower every developer to build, innovate and solve the world''s most pressing challenge," said Microsoft''s chief executive Satya Nadella in a statement.\r\n\r\nIt added that Github is currently used by more than 28 million developers, who in turn represent more than 1.5 million organisations across a range of industries.\r\n\r\nThe business will be led by Nat Friedman, the founder of Xamarin - a mobile software development service acquired by Microsoft in 2016.\r\n\r\nMicrosoft described Mr Friedman as being an "open source" veteran.\r\n\r\nThe term refers to the principle that code is made publicly accessible so that others can inspect, modify and share it.\r\nTakeover worries\r\n\r\n"Github offers transparency - it''s a very effective, no-fuss tool to run projects globally while allowing many developers to contribute," commented Malcolm Barclay, a UK-based app developer.\r\n\r\n"Some are nervous because of what Microsoft has done with past purchase', '../media/bsns1.jpg', '2018-06-04'),
(54, 'Airlines slash profit forecast as costs soar', 'Business', NULL, 'Profits at the world''s major airlines will be hit this year by rising fuel and labour costs, the industry''s trade body has said.\r\n\r\nThe International Air Transport Association has cut its profit forecast for 2018 by 12% to $33.8bn (Â£25.3bn).\r\n\r\nIATA, which is holding its annual meeting, said rising interest rates and trade tensions would also hit profits.\r\n\r\nAirlines earned a record $38bn in 2017, although this was distorted by several one-off changes, such as tax credits.\r\n\r\nDespite the reduced profit forecast, IATA''s director general, Alexandre de Juniac, said: "Solid profitability is holding up in 2018, despite rising costs. The industry''s financial foundations are strong with a nine-year run in the black that began in 2010."\r\n\r\nAirlines'' fuel costs this year are forecast to rise by nearly 30%, with the oil price expected to average $70 a barrel, up from $54.90 a barrel in 2017.\r\n\r\nIATA, which represents 280 airlines that make up about 83% of global traffic, had previously forecast an average price of $60 a barrel.\r\n\r\nMr de Juniac warned that airlines could be hit by the effects of "political forces pushing a protectionist agenda", although he did not mention any countries.\r\n\r\n"We haven''t faced any significant decline in numbers of passengers or cargo related to trade wars or protectionist barriers up to now, but if it continues it will happen," he told a news conference at the meeting, which is being held in Sydney.\r\n\r\nThe US and China have threatened tit-for-tat tariffs', '../media/bsns2.jpg', '2018-06-03'),
(55, 'Facebook protests NYT''s privacy breach claim', 'Business', NULL, 'ils were stored on the firms'' own servers.\r\n\r\nBut Facebook said that this was only done to help offer a mobile service.\r\n\r\nAnd it has said the circumstances were "very different" from those involved in the Cambridge Analytica scandal, in which user data was used for different purposes.\r\n\r\nEven so, the NYT raised concern that people''s information - including users'' relationship status, religion, political leaning and planned events - had been shared with other businesses.\r\n\r\nIt suggested the practice meant the Silicon Valley firm might have breached an agreement it struck with the Federal Trade Commission in 2011 to get consumers'' "express consent" before sharing personal data with third parties in new ways.\r\n\r\nFurthermore, it quoted an ex-FTC official saying that Facebook''s behaviour was at odds with privacy commitments it had made to the public in 2014.\r\nSigned agreements\r\n\r\nThe NYT carried out its own test with an old Blackberry phone to illustrate the issue.\r\n\r\nThe handset ran an app called Hub, which was designed to collate information from a variety of social media platforms into one place.\r\n\r\nThe newspaper said the information collected by the software included the IDs, birthday dates, work details and educational histories of many of the journalists'' friends, as well as identifying information about many more friends-of-friends.\r\n\r\nFacebook has responded with a blog headlined "Why we disagree with the New York Times".\r\n\r\nIt defended its use of software tools called app', '../media/bsns3.jpg', '2018-06-05'),
(56, ' James Gunn Says Guardians of the Galaxy 3 Is ''Very Different''', 'Movies', NULL, 'Guardians of the Galaxy Vol. 3 will be "very different" from its predecessors, director/writer James Gunn teases. The movie may not have a confirmed date yet (although rumor has it that it will take the May 2020 Marvel spot), but it has already starting to generate interest from Marvel fans especially considering that after Avengers: Infinity War, Rocket Raccoon and Nebula are the only remaining members of the team to be alive. That said, people can expect that most, if not all, of the members of the cosmic team will eventually be resurrected come Avengers 4.\r\n\r\nSeveral actors including Chris Pratt, Pom Klementieff and Dave Bautista have confirmed that they''re returning to reprise their respective roles - Star-Lord/Peter Quill, Mantis and Drax the Destroyer - in next year''s untitled Avengers, as well as Guardians 3. While it''s still a mystery how they''ll all return from the dead after they were snuffed out of existence due to Thanos'' snap, Gunn is already plotting their next adventure as an independent team.\r\n\r\nabove is fan made  trailer.', '../media/GUARDIANS OF THE GALAXY 3 Teaser Trailer (2019) Chris Pratt Action Movie HD [Fan Made].mp4', '2018-06-03'),
(57, 'Tom Cruise''s Latest Mission: Impossible Stunt Documented In New Video', 'Movies', NULL, 'Tom Cruise''s commitment to stunts, especially for his Mission: Impossible movies has long been a matter of public record. And in his never-ending quest to top the show-stopping moment from each film, he''s now taken to leaping out of planes for real. But not just any jump, a High Altitude, Low Opening, or Halo jump. Check out the video of him doing it more than once for Mission: Impossible â€“ Fallout below.\r\n\r\nYes, while we''re sure that leaping out of a plane travelling 165mph at 25,000 feet is fun and cool for Cruise (he had to do it several times so they could get the shot), we can only imagine the knots that director Christopher McQuarrie''s stomach is tying itself in as his friend and star makes each jump. Still, as writer on the current IM films and the person who develops these ideas with Cruise, he really only has himself to blame.\r\n\r\nFallout promises a mix of Missions past and present, with Sean Harris returning as Solomon Lane, captured by Cruise''s Ethan Hunt and team last time around. Of course, heâ€™s now escaped and is threatening Hunt with doomy, whispered warnings of incoming nuclear attacks. Among other returning faces are Ving Rhames as long-term IMF team member Luther, Alec Baldwin as the CIAâ€™s Alan Hunley, Simon Pegg as Benji, and Rebecca Ferguson reprising her Rogue Nation role of Ilsa Faust. Oh, and a new problem emerges in the shape of Henry Cavill''s Agency enforcer Tachley McLipp... er... August Walker.\r\n\r\nMission: Impossible: Fallout will be in cinemas', '../media/Mission Impossible Fallout  Halo Jump  Paramount Pictures UK.mp4', '2018-06-04');
INSERT INTO `news` (`Id`, `Title`, `genre`, `subGenre`, `Content`, `mediaPath`, `Date`) VALUES
(58, 'Amy Seimetz Joins The New Pet Sematary', 'Movies', NULL, 'We already know that Jason Clarke and John Lithgow will be leading the cast for a new adaptation of Stephen King''s horror tome Pet Sematary. Now Alien: Covenant''s Amy Seimetz is joining them.\r\n\r\nClarke is starring as Louis Creed, a father who moves his family (including his wife, Rachel, the role Seimetz is in talks for) to a new home, and strikes up a friendship with Crandall, who knows the secrets of the small town they''ve arrived in. When the family''s cat is killed in an accident, he guides them to a place beyond the local "pet sematary" (the spelling is in the book, based on how the neighbours have written the sign) and terrible things unspool from there.\r\n\r\nStarry Eyes directors Kevin Kolsch and Dennis Widmyer are attached to direct, with a script by Jeff Buhler.\r\n\r\nSeimetz, last seen in Lean On Pete, is part of the cast for Wild Nights With Emily, which has yet to find a UK date. ', '../media/movs.jpg', '2018-06-06'),
(59, ' Julianna Margulies Ditches the Heart and Goes for Broke in Dietland ', 'Intertainment', NULL, '\r\n\r\nA new red wig, a villainous role, a cable dramaâ€”it''s a new era for Julianna Margulies.\r\n\r\n"Oh, it was delicious!" the Emmy-winning actor said about her turn as icy magazine editor Kitty Montgomery in AMC''s Dietland. "It was really funâ€¦people always say it''s more fun to play a villainous role and I get it now."\r\n\r\nKnown to legions of fans for her tenure as Nurse Carol Hathaway on ER and most recently for her seven seasons as The Good Wife''s Alicia Florrick, Margulies took two years off from series regular TV work before landing at Dietland, a new drama from Marti Noxon. Kitty Montgomery is a far cry from the characters Margulies has become known for. Alicia Florrick she ain''t.\r\n\r\n"I think viewers will see her as a villain. Once I got to know her a little better, I think she truly believes she''s a wonderful person, but she''s such a narcissist she can''t see anything wrong with how she acts, which is completely and utterly unempathetic and brutal. She''s cutthroat, but then playing her and seeing how she had to fight her way to get to where she isâ€”and at the end of the day, even though she has brought this magazine from 0 to 100 in less than a year, she still has to answer to an all white male board, most of them over 60. So I got to understand her fight a little better, but yeah, I usually play the girl with the heart on the sleeve. And Kitty, I''m not sure if there''s a heart even inside," Margulies said.\r\n\r\n\r\n\r\nBased on the book of the same name by Sarai Walker, the AMC', '../media/ent1.jpg', '2018-06-04'),
(60, 'Janet Jackson Calls Police for Welfare Check on 1-Year-Old Son While With His Father', 'Intertainment', NULL, 'On Saturday night, Janet Jackson called police to do a welfare check on her 1-year-old son Eissa Al Mana, who was staying with her estranged ex-husband, Qatari billionaire and businessman Wissam Al Mana, at the Nobu Hotel in Malibu at the time, E! News can confirm.\r\n\r\nA watch commander with the Malibu County Sheriffâ€™s Office tells E! News that police responded to a call shortly before 10 p.m. at the Nobu Hotel, where they were asked to check on the welfare of Jackson''s son, who was with his father. \r\n\r\nThe police confirmed that Jackson was not on the scene at the time of the incident but that she was at the hotel when the police arrived. The watch commander added that everything checked out okay and when the police left and the child remained at the hotel.\r\n\r\n\r\n\r\nThe singer''s brother Randy Jackson spoke to ET regarding the phone call, and the outlet reported that the musician said his sister called 9-1-1 after a nanny who was helping Al Mana care for the child at the time called her. The nanny became frightened by Al Mana''s behavior which she believed was aggressive, according to Randy.\r\n\r\nRandy claims the nanny was "terrified by his behavior and locked herself in a bathroom, so she could contact Janet." \r\n\r\nJackson and Al Mana welcomed their son on Jan. 2, 2017. Three months later, the couple announced their split in April 2017 after five years of marriage.\r\n\r\n"Janet and Wissam don''t see eye to eye on many things," a source tells E! News at the time. "One of the many divor', '../media/ent2.jpg', '2018-06-05'),
(61, ' John Mayer: Jennifer Lawrence Wants Nothing to Do With Me ', 'Intertainment', NULL, '\r\n\r\nJohn Mayer is looking for loveâ€”and Andy Cohen is no help at all.\r\n\r\nIn honor of the host''s 50th birthday, the "New Light" singer made a surprise appearance on Cohen''s late-night show Sunday. During the after-show, Mayer turned the tables and put Cohen in the hot seat. At one point, he said, "You have a lot of friends who, without you, would want nothing to do with meâ€”and I find that exciting! You know what I mean? You''re friends with Jennifer Lawrence, who just doesn''t want anything to do with me. Look, I don''t have the world''s greatest track record when it comes to celebrity relationships, so it''s amazing to watch your friends humor me on a friend level, but also keep a fair distance from me. It''s really, really fun, because if you are someone who cares about your imageâ€”and you take this job because it looks right, you don''t take that jobâ€”dating John Mayer at this point is conceptually just sort of a no-no. So, it''s really fun to get to hang out with your friendsâ€”A-list star friendsâ€”who otherwise would be highly uncomfortable sitting around me. And I want to thank you for that."\r\n\r\n\r\n\r\nReferencing Mayer''s song, Cohen said, "I want them to see you in the new light that I see you."\r\n\r\nMayerâ€”whose exes include Jennifer Aniston, Jennifer Love Hewitt, Minka Kelly, Katy Perry, Jessica Simpson and Taylor Swiftâ€”joked his is "slowly but surely" setting himself up "for another disastrous celebrity relationship so that I can wake a month later and be back 10 years i', '../media/ent3.jpg', '2018-06-06'),
(62, 'Ambien maker to Roseanne: ''Racism is not a known side effect''', 'Culture', NULL, 'Just hours after quitting Twitter over the fallout from her racist comments, Roseanne Barr was back on social media explaining her offensive comments. She blamed it on the Ambien.\r\n\r\n"Guys I did something unforgiveable so do not defend me," Roseanne wrote. "It was 2 in the morning and I was ambien tweeting-it was memorial day too-I went 2 far & do not want it defended-it was egregious Indefensible. I made a mistake I wish I hadn''t butâ€¦don''t defend it please."\r\n\r\nIt''s been reported that Ambien causes people to drive, cook, eat, talk, shop and have sex without remembering any of it. Tweeting under the influence of Ambien certainly could happen. But doctors â€” and Sanofi, the drug maker that manufacturers the sleep aid â€” agree that the drug doesn''t cause racism.\r\nSanofi, admits that "getting out of bed while not being fully awake and do an activity that you do not know you are doing" is a side-effect of using the drug. The company urges people to call their doctors if they experience this, which is also known as a parasomnia. But Sanofi also pushed back against Roseanne.\r\n\r\n"While all pharmaceutical treatments have side effects, racism is not a known side effect of any Sanofi medication," the company shared on Twitter early Wednesday.\r\n\r\n"Maybe Roseanne was taking Ambien when she Tweeted. Maybe. Sleep medications don''t create these beliefs. They unmask them," W. Christopher Winter, a sleep medicine doctor at Charlottesville Neurology and Sleep Medicine and author of The Sle', '../media/cult1.jpg', '2018-06-03'),
(63, 'Reggae star Ziggy Marley releases new solo album', 'Culture', NULL, '\r\n\r\nHe said he took lessons from his father''s "Exodus" as he was crafting the album.\r\n\r\n"It is a rebellion of love, rebellion of more peace, the rebellion of more unity, the rebellion of less discrimination," Marley explained. "This is a rebellion ... this album to me is a voice or a force to help to push that forward because in one of the songs I say ''only the willing will see their dreams''."\r\n\r\nMarley started writing and recording Rebellion Rises during the US election season, and filtered his frustrations with politics through largely upbeat songs with swinging reggae rhythms.\r\n\r\n"There''s so much fake leaders in Africa right now. The continent of Africa that should be unified, that have so much wealth, that have so much richness. Why is the people of Africa suffering so much? Because lack of leadership in Africa.\r\n\r\n"There isn''t a lot of music out there where people really give a message right now or speaks to humanity as a whole. Rebellion Rises, for me, is the voice of humanity in a way," he said.\r\n\r\nMarley recorded with just a handful of musicians, and his only formal guests on the collection of 10 songs are his wife, son and daughter.\r\n', '../media/cult2.jpg', '2018-06-05'),
(64, 'Pulitzer prize for US rapper Lamar', 'Culture', NULL, 'American rapper Kendrick Lamar has made history by becoming the first hip hop musician to receive the prestigious Pultizer Prize for music for his acclaimed album Damn.\r\n\r\nIn making the award, the album was described as a "virtuosic song collection ... which captured the complexity of modern African American life.â€\r\n\r\nThe album, launched last year, has been a huge critical and commercial succes and has received many international awards including a Grammy for Best Rap album.\r\n\r\nPulitzer winners do not make acceptance speeches, but in a Facebook Live video on the Pulitzer Prizes page, Lamar told Sree Sreenivasan, â€œIâ€™ve been writing my whole life, so to get this type of recognition â€• itâ€™s beautiful.â€\r\n\r\nThe Pulitzer Prizes date to 1917 and honor outstanding work in journalism and the arts, letters and music. The first Pulitzer for music was awarded in 1943 to William Schuman for â€œSecular Cantata No. 2: A Free Song.â€\r\n', '../media/cult3.jpg', '2018-06-05'),
(65, 'Tips, links and suggestions: what are you reading this week?', 'Books', NULL, 'Welcome to this weekâ€™s blog. Hereâ€™s our roundup of your comments and photos from last week.\r\n\r\nFirst up, Veufveuve asks us to believe the hype about Barracoon: The Story of the Last â€œBlack Cargoâ€ by Zora Neale Hurston:\r\n\r\n    This book, which had lain unpublished since it was completed by Hurston in the early 1930s, has attracted much excitement and expectation since it was announced earlier this year. It deserves every ounce of hype and praise it has received. Based on oral history interviews conducted by Hurston, it tells the story of Cudjo Lewis, or Kossula, one of the last survivors of one of the last slavers, the Clotilda, to reach the US. It is a remarkable testament; everything one knows about slavery in an abstract sense is painfully, vividly embodied here in Kossula, still utterly bereft of Africa nearly 70 years after he was snatched away from it. Nothing could bring the psychological or emotional damage of that dislocation closer. The narrative, largely in Kossulaâ€™s own words (rendered in dialect but extremely easy to understand), is handled beautifully by Hurston. Sympathetically put together with a foreword, introduction, afterword, glossary, notes etc, this book needs to read as widely as possible.\r\n\r\nRose Tremainâ€™s Restoration has impressed PlumedCrest100:\r\n\r\n    It is a wonderfully humorous book, but it is desperately sad in parts. Tremain captures the colourfulness and the spirit of the restoration era well, her descriptions of food, clothes and e', '../media/book1.jpg', '2018-06-12'),
(66, ' Are literary classics behind the misogyny of the incel movement?', 'Books', NULL, 'One month ago, Alek Minassian drove through a Toronto shopping district in a rented van, killing 10 people and injuring 16 more. Analysis of Minassianâ€™s online activity â€“ where he participated in forums for the involuntarily celibate, or incels â€“ quickly revealed the attackâ€™s motivation: he was avenging himself on the women (apparently all of us) who had rejected him. He declared that with his act of terrorism, the â€œincel rebellionâ€ had begun â€“ although he was not the first self-described incel to use his sexlessness as an excuse for acts of mass violence.\r\n\r\nThough the subsequent rash of media analysis might lead you to think otherwise, none of this is new â€“ not even the term â€œincelâ€, which was first coined in 1993 by a queer Canadian woman when she created a website for people who identified as involuntary celibates to share their thoughts and feelings. The incel community that exists today on reddit, 4chan and incel.me is an inchoate and ever-evolving group, which seems to change shape with every attempt to characterize it. The genealogy of todayâ€™s incel grows more complex the more you dig (he is descended from both the aggressively misogynist pick-up artist community and the slightly more sympathetic â€œlove-shyâ€ community). What members of all these groups share, of course, is their sense of their own alienation from women and their (almost always deeply misogynistic) conviction that this alienation has negatively affected their lives in myriad pr', '../media/book2.jpg', '2018-05-29'),
(67, ' Marian Keyes attacks ''sexist imbalance'' of Wodehouse prize', 'Books', NULL, 'Marian Keyes has revealed that she has a â€œgrudgeâ€ against the â€œsexist imbalanceâ€ of the Wodehouse prize for comic fiction, which has deemed only three female writers funny enough to win the award in 18 years.\r\n\r\nKeyes was speaking at the Hay literary festival, where the winner of the Bollinger Everyman Wodehouse award for comic fiction is traditionally announced. This year, however, judges declined to award the prize, announcing in May that none of the 62 books submitted â€œincited the level of unanimous laughter we have come to expectâ€.\r\n\r\nAccording to the Telegraph, Keyes told an audience at the Hay festival: â€œSay what you like about me but my books are funny. What more can I do to qualify?â€ The bestselling novelist, whose latest book The Break was described as â€œmercilessly funnyâ€ by the Times but who has never been shortlisted for the Wodehouse prize, was being interviewed for the BBC News Channelâ€™s Talking Books programme.\r\n\r\n\r\nOnly three female writers â€“ Helen Fielding, Marina Lewycka and Hannah Rothschild â€“ have won the Wodehouse since it was launched in 2000. Male writers dominate the comic prize, said Keyes, â€œbecause theyâ€™re men. Because male voices are automatically given extra weight. I mean, anything thatâ€™s ever been said or done by a woman just matters less.â€\r\n\r\nKeyes, who admitted that she had been told by â€œwell-meaning typesâ€ that â€œif you just knock off the humour, youâ€™ll be taken seriouslyâ€, told the audience: â€œThings', '../media/book3.jpg', '2018-06-05'),
(68, ' A family at war: saving my granddaughter from FGM', 'Blogs', NULL, 'For those who do not know her, Ban Soon-taek is a quiet first lady, married to the secretary general of the United Nations but rarely vocal on global issues. She showed another side, as a champion of human rights equalling her more famous husband, at a recent event on ending female genital mutilation (FGM).\r\n\r\nHer ringing call to â€œend harmful traditional practices and unleash the power of young girlsâ€ came on at an event organised in the margins of the UN Commission on the Status of Women in New York on 18 April. She thanked participants for endeavouring to â€œchange a harmful tradition into an empowering missionâ€.\r\n\r\n    Mutilation would have been a terrible violation of our daughter''s rights \r\n\r\nBan took her inspiration from a meeting organised by the Guardian between her husband and the young British anti-FGM activist Fahma Mohamad two years before in London. She paid tribute to this newspaperâ€™s contributions, expressing hope that the media would continue to â€œhelp us spread the message that girls need education, not mutilationâ€.\r\n\r\nAs chair of the event, I listened with great interest as Ban spoke about how Fahma was reaching out to address risks to Diaspora communities in developed countries where most people are unaware that FGM is a threat. Her efforts mirror those of my own organisation, Finally Girls Matter, which I founded along with my daughter to protect women and girls of all ages and in all places â€“ including in societies where the practice is large', '../media/blog1.jpg', '2018-06-03'),
(69, ' New South Wales'' new logo and slogan slips by unnoticed â€“ almost', 'Blogs', NULL, 'When Victoria unveiled its new state logo and tagline to much fanfare in August, the New South Wales premier, Mike Baird, was quick to get a jibe in.\r\n\r\nBut at least people noticed Victoria had a new logo.\r\n\r\nPerhaps wary of similar negative publicity, New South Wales seems to have changed its corporate branding with no fanfare at all.\r\n\r\nIn fact, the new logo and slogan appear to have been in place for at least a week. Thatâ€™s at least a week in which Baird has managed to avoid a witty retort from Victoriaâ€™s premier, Daniel Andrews.\r\n\r\nThe earliest reported sighting of the logo was at a press conference in Martin Place on 2 September, but ABC Sydneyâ€™s photo of it was met with a straight-faced response on Twitter: just one retweet.\r\n\r\nâ€œThe definition of designed by committee,â€ tweeted The Feed host Marc Fennell.\r\n\r\n\r\nThough the state government website and branding guidelines were on Thursday still showing the old waratah logo, a spokesman told Guardian Australia that there had been no attempt to conceal the â€œfreshening up of the state brandâ€.\r\n\r\nâ€œVictoria had a huge campaign and a huge launch, costing a huge amount of money. Weâ€™re just quietly filtering it through into the different bunting and branding and so on.\r\n\r\nâ€œWe havenâ€™t made a big deal out of it, but weâ€™re certainly not trying to conceal or hide it.â€ He agreed that it was something of a â€œsoft launchâ€.\r\n\r\nWhen asked what â€œitâ€ was that New South Wales was making happen, the spokesman s', '../media/blog2.jpg', '2018-06-05'),
(70, ' Life after disappointing exam results: share your positive stories', 'Blogs', NULL, 'Not everyone finds themselves jumping in the air on exam results day for an enthusiastic newspaper photographer. While some students receive the grades they want, others will be more than disappointed.\r\n\r\nA levels and GCSEs are great markers in our lives, with the former signalling the end of thirteen years of school education. There is a lot to celebrate. But for those of us who donâ€™t make the grades it can be hard to see a way forward.\r\n\r\nGrades fell slightly last year, but does this mean that more people will fail to go on to have fulfilling lives? No, it doesnâ€™t. I got an E in textiles. But it all worked out okay in the end.\r\n\r\nDid you receive less than desirable GCSE or A Level results? What happened next? We want to hear your positive stories for a feature on the site.\r\n\r\nFill in the form below, or email: carmen.fishwick@theguardian.com\r\nSince youâ€™re here â€¦\r\n\r\nâ€¦ we have a small favour to ask. More people are reading the Guardian than ever but advertising revenues across the media are falling fast. And unlike many news organisations, we havenâ€™t put up a paywall â€“ we want to keep our journalism as open as we can. So you can see why we need to ask for your help. The Guardianâ€™s independent, investigative journalism takes a lot of time, money and hard work to produce. But we do it because we believe our perspective matters â€“ because it might well be your perspective, too.\r\n\r\n    I appreciate there not being a paywall: it is more democratic for the media to ', '../media/blog3.jpeg', '2018-06-06');

-- --------------------------------------------------------

--
-- Table structure for table `newsletter`
--

CREATE TABLE `newsletter` (
  `Id` int(4) NOT NULL,
  `Name` varchar(30) NOT NULL,
  `Email` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `newsletter`
--

INSERT INTO `newsletter` (`Id`, `Name`, `Email`) VALUES
(1, 'lfkfkl', 'fdkljfAddress');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `username` varchar(20) NOT NULL,
  `password` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`username`, `password`) VALUES
('admin', 'admin');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `newsletter`
--
ALTER TABLE `newsletter`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`username`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contact`
--
ALTER TABLE `contact`
  MODIFY `Id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
--
-- AUTO_INCREMENT for table `news`
--
ALTER TABLE `news`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=73;
--
-- AUTO_INCREMENT for table `newsletter`
--
ALTER TABLE `newsletter`
  MODIFY `Id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
